services:

  ctinexus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=8000
    env_file:
      - .env
    networks:
      - ctinexus_network
    volumes:
      - ./app:/app  # Mount local code for development (optional)

networks:
  ctinexus_network:
    driver: bridge

volumes:
  falkordb_data: