defaults:  
  - base
  - _self_

# basic setting
inSet: output/ET-output-preprocessed
outSet: output/EM-output

# LLM setting
embedding_model: text-embedding-3-large #choose your embedding model

# Merging setting
similarity_threshold: 0.6 #choose your similarity threshold